### ISSUE TITLE
ValueError: Exception encountered when calling layer "attention" (type Attention)

### ISSUE THREAD

**Issue by thangld201** [taoqi98/HieRec#4]
Hi, I tried to copy all modules onto a google colab notebook and also added the KG Data for Small MIND dataset. However, when I run the notebook the following error pops up:

```
ValueError                                Traceback (most recent call last)
<ipython-input-26-0a1ef422da03> in <module>()
----> 1 model,news_encoder,user_encoder,rews = create_model(category_dict,subcategory_dict,title_word_embedding_matrix,entity_emb_matrix)
      2 Res.append({'AUC':[],'MRR':[],'nDCG5':[],'nDCG10':[]})
      3 train_generator = get_hir_train_generator(0.9999,news_info,index2nid,news_vert,news_subvert,news_entity_np,news_entity,train_user['click'],train_user_id,train_sess,train_label,16)
      4 model.fit_generator(train_generator,epochs=4,verbose=3)
      5 

3 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    697       except Exception as e:  # pylint:disable=broad-except
    698         if hasattr(e, 'ag_error_metadata'):
--> 699           raise e.ag_error_metadata.to_exception(e)
    700         else:
    701           raise

ValueError: Exception encountered when calling layer "attention" (type Attention).

in user code:

    File "<ipython-input-10-c62a5f68bc7e>", line 55, in call  *
        A = K.permute_dimensions(A, (0,3,2,1))
    File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 3288, in permute_dimensions
        return tf.compat.v1.transpose(x, perm=pattern)

    ValueError: Dimension must be 5 but is 4 for '{{node attention/transpose_7}} = Transpose[T=DT_FLOAT, Tperm=DT_INT32](attention/truediv, attention/transpose_7/perm)' with input shapes: [?,20,30,20,30], [4].


Call arguments received:
  • x=['tf.Tensor(shape=(None, 30, 300), dtype=float32)', 'tf.Tensor(shape=(None, 30, 300), dtype=float32)', 'tf.Tensor(shape=(None, 30, 300), dtype=float32)']
```

**Steps to reproduce the error**: connect to the following notebook  https://colab.research.google.com/drive/1h88uAM3MIi0htHJoJiY9cRMJ3jo0lrLu?usp=sharing and click Run All. 
I did modify the tensorflow import (use tf.compat.v1. instead of tf. for some imports) since Colab uses Tensorflow v2 by default. I realized that either tensorflow v1 and v2 both lead to the above-mentioned error. If possible, could you check if the original code still works ? I tried to debug the program but couldn't find the cause.

**Comment by taoqi98** [comment]
This is caused by the inconsistent version of tf and keras. The code can be executed under  (1) tensorflow-gpu == 1.13.0 (2) keras == 2.2.4
